export type MockStatus = "Draft" | "Pending Approval" | "Approved" | "Scheduled" | "In Progress" | "Completed" | "Cancelled" | "Rejected" | "Published";
export type MockRole = "Super Admin" | "Meeting Secretary" | "Faculty / Officer" | "Member" | "Auditor";

export type MockMeeting = { id: string; title: string; date: string; location: string; type: "Board" | "Committee" | "Review"; status: MockStatus; approver: string; createdBy: string; description: string; agenda: string[] };
export type MockParticipant = { id: string; name: string; email: string; role: MockRole; attendance: "Present" | "Absent" | "Pending" };
export type MockAction = { id: string; task: string; assignee: string; deadline: string; priority: "Low" | "Medium" | "High" | "Critical"; status: "Open" | "In Progress" | "Completed" | "Overdue" };
export type MockDecision = { id: string; decision: string; description: string; date: string; responsible: string; status: "Proposed" | "Approved" | "Rejected" | "Implemented" };
export type MockEvent = { id: string; title: string; date: string; location: string; description: string; organizer: string; status: "Upcoming" | "Ongoing" | "Completed" | "Cancelled" };
export type MockPolicy = { id: string; title: string; category: string; version: number; owner: string; status: "Draft" | "Under Review" | "Approved" | "Published" | "Archived"; updated: string; effectiveDate: string; content: string };
export type MockUser = { id: string; name: string; email: string; role: MockRole; department: string; status: "Active" | "Invited" | "Suspended"; lastActive: string };

export const mockMeetings: MockMeeting[] = [
  { id: "m-001", title: "Academic Council Review", date: "2026-09-28T10:00:00+05:30", location: "Senate Hall", type: "Board", status: "Pending Approval", approver: "Dr. Ishika Sharma", createdBy: "Isha Mewada", description: "Review academic calendar and curriculum proposals.", agenda: ["Academic calendar", "Curriculum proposals", "Faculty workload"] },
  { id: "m-002", title: "Budget & Finance Committee", date: "2026-10-02T14:30:00+05:30", location: "Finance Conference Room", type: "Committee", status: "Scheduled", approver: "Dr. Ishika Sharma", createdBy: "Akshat Jaiswal", description: "Quarterly budget review and allocation planning.", agenda: ["Quarterly variance", "Capital requests"] },
  { id: "m-003", title: "Research Governance Review", date: "2026-08-19T11:00:00+05:30", location: "Online", type: "Review", status: "Completed", approver: "Dr. Ishika Sharma", createdBy: "Isha Mewada", description: "Research ethics and grant compliance review.", agenda: ["Ethics register", "Grant compliance", "Open actions"] },
];
export const mockParticipants: MockParticipant[] = [{ id: "u-001", name: "Akshat Jaiswal", email: "akshatjaiswal875@gmail.com", role: "Super Admin", attendance: "Present" }, { id: "u-002", name: "Isha Mewada", email: "ishamewada5@gmail.com", role: "Meeting Secretary", attendance: "Present" }, { id: "u-003", name: "Ishika Sharma", email: "ishikasharma200811@gmail.com", role: "Faculty / Officer", attendance: "Pending" }];
export const mockActions: MockAction[] = [{ id: "a-001", task: "Circulate revised academic calendar", assignee: "Isha Mewada", deadline: "2026-10-01", priority: "High", status: "Open" }, { id: "a-002", task: "Prepare finance variance note", assignee: "Akshat Jaiswal", deadline: "2026-10-04", priority: "Medium", status: "In Progress" }, { id: "a-003", task: "Archive completed ethics review", assignee: "Ishika Sharma", deadline: "2026-08-30", priority: "Low", status: "Completed" }];
export const mockDecisions: MockDecision[] = [{ id: "d-001", decision: "Adopt revised academic calendar", description: "Calendar will take effect from the next academic cycle.", date: "2026-09-28", responsible: "Isha Mewada", status: "Approved" }, { id: "d-002", decision: "Increase research review cadence", description: "Move governance review to a monthly cadence.", date: "2026-08-19", responsible: "Ishika Sharma", status: "Implemented" }];
export const mockEvents: MockEvent[] = [{ id: "e-001", title: "Faculty Senate", date: "2026-09-29T09:00:00+05:30", location: "Senate Hall", description: "Monthly faculty senate session.", organizer: "Isha Mewada", status: "Upcoming" }, { id: "e-002", title: "Governance Induction", date: "2026-09-24T16:00:00+05:30", location: "Online", description: "Orientation for new committee members.", organizer: "Akshat Jaiswal", status: "Completed" }];
export const mockPolicies: MockPolicy[] = [{ id: "p-001", title: "Research Ethics & Integrity", category: "Research", version: 3, owner: "Ishika Sharma", status: "Published", updated: "2026-09-12", effectiveDate: "2026-10-01", content: "This policy defines institutional expectations for ethical research, review, reporting, and accountability." }, { id: "p-002", title: "Records Retention Standard", category: "Governance", version: 1, owner: "Akshat Jaiswal", status: "Under Review", updated: "2026-09-21", effectiveDate: "2026-11-01", content: "Institutional records must be retained, classified, and disposed of according to approved schedules." }];
export const mockUsers: MockUser[] = [{ id: "u-001", name: "Akshat Jaiswal", email: "akshatjaiswal875@gmail.com", role: "Super Admin", department: "Administration", status: "Active", lastActive: "Just now" }, { id: "u-002", name: "Isha Mewada", email: "ishamewada5@gmail.com", role: "Meeting Secretary", department: "Secretariat", status: "Active", lastActive: "12 min ago" }, { id: "u-003", name: "Ishika Sharma", email: "ishikasharma200811@gmail.com", role: "Faculty / Officer", department: "Research", status: "Active", lastActive: "1 hr ago" }, { id: "u-004", name: "Rohan Mehta", email: "rohan.mehta@example.com", role: "Member", department: "Finance", status: "Invited", lastActive: "Never" }];
